# Configuration for Alacritty, the GPU-enhanced terminal emulator.

[window]
# Window dimensions (change to your preferred size)
dimensions = { columns = 100, lines = 30 }
# Position of the window on startup (x, y)
position = { x = 10, y = 10 }
# Set to `true` if you want the window to be maximized on startup
maximized = false
# Window background opacity (from 0.0 to 1.0)
opacity = 0.9
# Disable window decorations
decorations = "full"

[font]
# Normal (roman) font face
normal = { family = "Fira Code", style = "Regular" }
# Bold font face
bold = { family = "Fira Code", style = "Bold" }
# Italic font face
italic = { family = "Fira Code", style = "Italic" }
# Font size
size = 12.0

[colors]
[colors.primary]
background = '0x282a36'
foreground = '0xf8f8f2'

[colors.normal]
black = '0x21222c'
red = '0xff5555'
green = '0x50fa7b'
yellow = '0xf1fa8c'
blue = '0xbd93f9'
magenta = '0xff79c6'
cyan = '0x8be9fd'
white = '0xbfbfbf'

[colors.bright]
black = '0x4d4d4d'
red = '0xff6e6e'
green = '0x69ff94'
yellow = '0xffffa5'
blue = '0xd6acff'
magenta = '0xff92df'
cyan = '0xa4ffff'
white = '0xffffff'

[colors.cursor]
text = '0x000000'
cursor = '0xffffff'

[cursor]
style = "Beam"

[bell]
animation = "Ease"
duration = 0

[scrolling]
history = 10000
multiplier = 3

[[mouse_bindings]]
mouse = "Middle"
action = "PasteSelection"

[[key_bindings]]
key = "V"
mods = "Control|Shift"
action = "Paste"

[[key_bindings]]
key = "C"
mods = "Control|Shift"
action = "Copy"

[[key_bindings]]
key = "N"
mods = "Control|Shift"
action = "SpawnNewInstance"

[[key_bindings]]
key = "Return"
mods = "Alt"
action = "ToggleFullscreen"

[background_opacity]
opacity = 0.9
blur = false
